POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ildhc2QiLCJpZCI6IjYwZjgyYzNhY2Q0YWY3M2RlNDBhYjMwMCIsImlhdCI6MTYyNjg3NzczMH0.QLSl2ZZr0zFuX5F40PFs-dG1D8s4IF7ielq5i4zEUDo

{
    "title": "Kala",
    "author": "Kala Kalkkuna",
    "url": "kala.fi",
    "likes": 401
}