POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Kissa",
    "author": "Kissa Kala",
    "url": "kissa.fi",
    "likes": 55,
    "userId": "60f817b0e8be7402206c3a86"
}