POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFhYUBFZWUuT29vIiwiaWQiOjMsImlhdCI6MTY0NzQ0MDEwOX0.ncBQY73Yu1IvnzHuMsxSDpB345VE2lfVNww3GHwwllk

{
    "author": "Dummy",
    "url": "asd.asd",
    "title": "Blog",
    "year": 1991
}